version: '3.9'
services:
  open-webui:
      image: 'ghcr.io/open-webui/open-webui:main'
      restart: always
      container_name: open-webui
      volumes:
        - './open-webui:/app/backend/data'
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      ports:
        - '3000:8080'
