version: '3.7'

services:

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
      - "COLLECTOR_OTLP_ENABLED=true"
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"