version: "3.1"

services:
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssword18"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: