global:
  scrape_interval: 30s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090']
  
  - job_name: node-exporter
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true

    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true

    static_configs:
    - targets: ['cadvisor:8080']
