version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: file-browser
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 7979:80
    volumes:
      - /home/duc/Storage/:/srv
      - ./filebrowser.db:/database.db
      - ./settings.json:/config/settings.json
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --disable-preview-resize --disable-thumbnails --disable-type-detection-by-header --cache-dir /media/duc/Temp
