version: "3.1"
services:
  db:
    image: docker.io/postgres:14.17
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: storage
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./init-data/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql"
